children:
  Applications:
    Atom: "atom"
    Firefox: "firefox"
    Firefox (Private window): "firefox --private-window www.duckduckgo.com"
    Package Manager: "$package_manager"
    Terminal: "$terminal"
  Awesome:
    Hotkeys: "#hotkeys"
    Edit: "$editor ~/.config/awesome"
    Restart: "#restart"
  System:
    Shutdown: "shutdown -P"
    Reboot: "reboot"
    Halt: "shutdown -H"
