children:
  Applications:
    Atom: "atom"
    Firefox: "firefox www.duckduckgo.com"
    Firefox (Private window): "firefox --private-window www.duckduckgo.com"
    Package Manager: "$package_manager"
    Terminal: "$terminal"
  Awesome:
    Hotkeys: "#hotkeys"
    Edit: "$editor ~/.config/awesome"
    Restart: "#restart"
  End Session: "$session_logout"
